package com.example.demo.mock;

import com.example.demo.post.domain.Post;
import com.example.demo.post.service.port.PostRepository;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

public class FakePostRepository implements PostRepository {

    // JPA의 save 메서드를 실행했을 때 자동으로 생성되는 아이디 값을 위한 값 (단위 테스트는 단일 스레드로 동작하기 때문에 동시성을 고려하지 않음)
    private long autoGeneratedId = 1;
    // 테스트를 위한 영속성 컨텍스트 직접 구현 (단위 테스트는 단일 스레드로 동작하기 때문에 동시성을 고려하지 않음)
    private final List<Post> data = new ArrayList<>();

    @Override
    public Optional<Post> findById(long id) {
        return data.stream().filter(item -> item.id().equals(id)).findAny();
    }

    @Override
    public Post save(Post post) {
        if(post.id() == null || post.id() == 0) {
            Post newPost = Post.builder()
                    .id(autoGeneratedId++)
                    .content(post.content())
                    .createdAt(post.createdAt())
                    .modifiedAt(post.modifiedAt())
                    .writer(post.writer())
                    .build();
            data.add(newPost);
            return newPost;
        }else {
            data.removeIf(item -> Objects.equals(item.id(), post.id()));
            data.add(post);
            return post;
        }
    }
}
